// Code generated by "stringer -type=TransactionType"; DO NOT EDIT.

package tasks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fail-0]
	_ = x[Completed-1]
}

const _TransactionType_name = "FailCompleted"

var _TransactionType_index = [...]uint8{0, 4, 13}

func (i TransactionType) String() string {
	if i < 0 || i >= TransactionType(len(_TransactionType_index)-1) {
		return "TransactionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransactionType_name[_TransactionType_index[i]:_TransactionType_index[i+1]]
}
