// Code generated by "stringer -type=TaskType"; DO NOT EDIT.

package edgeapi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PingHost-0]
	_ = x[InstallApp-1]
	_ = x[RemoveApp-2]
}

const _TaskType_name = "PingHostInstallAppRemoveApp"

var _TaskType_index = [...]uint8{0, 8, 18, 27}

func (i TaskType) String() string {
	if i < 0 || i >= TaskType(len(_TaskType_index)-1) {
		return "TaskType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskType_name[_TaskType_index[i]:_TaskType_index[i+1]]
}
